services:
  lab:
    build: .
    # image: jupyter/datascience-notebook
    ports:
      - "8888:8888"
      - "6006:6006"
    runtime: nvidia
    volumes:
      - ..:/home/jovyan/DAG-EQ
      - dotjulia:/home/jovyan/.julia
      - dotR:/home/jovyan/R
#     links:
#       - redis
#   redis:
#     image: redis
volumes:
  dotjulia: {}
  dotR: {}